name: labelstudio-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - requests
  - pip:
    - label-studio>=1.10.0
    - label-studio-ml>=1.0.9
    - pyinstaller>=6.3
    - pyinstaller-hooks-contrib>=2024.0