"""
RTTM Handler Module

This module handles the creation and processing of RTTM (Rich Transcription Time Marked) files
for speaker diarization results. RTTM is a standard format used in speaker diarization
evaluation and annotation systems.

RTTM Format:
SPEAKER <file-id> <channel-id> <start-time> <duration> <ortho> <stype> <speaker-id> <conf> <slat>

Where:
- file-id: Audio file identifier
- channel-id: Channel number (usually 1)
- start-time: Start time in seconds
- duration: Duration in seconds
- ortho: Orthographic transcription (usually <NA>)
- stype: Speaker type (usually <NA>)
- speaker-id: Speaker identifier
- conf: Confidence score (usually <NA>)
- slat: Speaker label type (usually <NA>)
"""

import os
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime
import json

logger = logging.getLogger(__name__)

class RTTMHandler:
    """
    Handler for RTTM (Rich Transcription Time Marked) file operations.
    
    This class provides methods to create, read, validate, and manipulate
    RTTM files for speaker diarization results.
    """
    
    def __init__(self, output_directory: Optional[str] = None):
        """
        Initialize the RTTM handler.
        
        Args:
            output_directory (Optional[str]): Directory for output files
        """
        self.output_directory = Path(output_directory or "outputs/rttm")
        self.output_directory.mkdir(parents=True, exist_ok=True)
        
        logger.info(f"RTTMHandler initialized with output directory: {self.output_directory}")
    
    async def create_rttm_file(self, 
                             diarization_result: Dict[str, Any],
                             audio_file_path: str,
                             job_id: Optional[str] = None) -> Path:
        """
        Create an RTTM file from diarization results.
        
        Args:
            diarization_result (Dict[str, Any]): Diarization results with segments
            audio_file_path (str): Path to the original audio file
            job_id (Optional[str]): Job identifier for filename
            
        Returns:
            Path: Path to the created RTTM file
        """
        try:
            # Generate filename
            audio_file = Path(audio_file_path)
            if job_id:
                rttm_filename = f"{job_id}_{audio_file.stem}.rttm"
            else:
                rttm_filename = f"{audio_file.stem}.rttm"
            
            rttm_path = self.output_directory / rttm_filename
            
            # Create RTTM content
            rttm_content = self._generate_rttm_content(diarization_result, audio_file.stem)
            
            # Write RTTM file
            with open(rttm_path, 'w') as f:
                f.write(rttm_content)
            
            logger.info(f"RTTM file created: {rttm_path}")
            
            # Also create a metadata file
            await self._create_metadata_file(rttm_path, diarization_result, audio_file_path)
            
            return rttm_path
            
        except Exception as e:
            logger.error(f"RTTM file creation failed: {e}")
            raise RuntimeError(f"Cannot create RTTM file: {e}")
    
    def _generate_rttm_content(self, diarization_result: Dict[str, Any], file_id: str) -> str:
        """
        Generate RTTM file content from diarization results.
        
        Args:
            diarization_result (Dict[str, Any]): Diarization results
            file_id (str): File identifier for RTTM
            
        Returns:
            str: RTTM file content
        """
        rttm_lines = []
        
        # Add header comment
        rttm_lines.append(f";; RTTM file generated by ALF Diarization System")
        rttm_lines.append(f";; File: {file_id}")
        rttm_lines.append(f";; Generated: {datetime.now().isoformat()}")
        rttm_lines.append(f";; Number of speakers: {diarization_result['num_speakers']}")
        rttm_lines.append(f";; Total segments: {diarization_result['total_segments']}")
        rttm_lines.append("")
        
        # Process each segment
        for segment in diarization_result['segments']:
            start_time = segment['start']
            duration = segment['duration']
            speaker_id = segment['speaker']
            confidence = segment.get('confidence', '<NA>')
            
            # Format confidence score
            if isinstance(confidence, float):
                conf_str = f"{confidence:.4f}"
            else:
                conf_str = "<NA>"
            
            # Create RTTM line
            # Format: SPEAKER <file-id> <channel> <start> <duration> <ortho> <stype> <speaker> <conf> <slat>
            rttm_line = f"SPEAKER {file_id} 1 {start_time:.3f} {duration:.3f} <NA> <NA> {speaker_id} {conf_str} <NA>"
            rttm_lines.append(rttm_line)
        
        return "\\n".join(rttm_lines)
    
    async def _create_metadata_file(self, 
                                  rttm_path: Path,
                                  diarization_result: Dict[str, Any],
                                  audio_file_path: str):
        """
        Create a metadata file alongside the RTTM file.
        
        Args:
            rttm_path (Path): Path to the RTTM file
            diarization_result (Dict[str, Any]): Diarization results
            audio_file_path (str): Original audio file path
        """
        try:
            metadata = {
                'rttm_file': str(rttm_path),
                'audio_file': audio_file_path,
                'created': datetime.now().isoformat(),
                'diarization_metadata': {
                    'num_speakers': diarization_result['num_speakers'],
                    'total_segments': diarization_result['total_segments'],
                    'total_speech_time': diarization_result['total_speech_time'],
                    'avg_segment_duration': diarization_result['avg_segment_duration'],
                    'processing_time_seconds': diarization_result['processing_time_seconds'],
                    'pipeline_version': diarization_result['pipeline_version']
                },
                'parameters_used': diarization_result['parameters_used'],
                'speakers': diarization_result['speakers']
            }
            
            metadata_path = rttm_path.with_suffix('.json')
            
            with open(metadata_path, 'w') as f:
                json.dump(metadata, f, indent=2)
            
            logger.info(f"Metadata file created: {metadata_path}")
            
        except Exception as e:
            logger.error(f"Metadata file creation failed: {e}")
    
    def read_rttm_file(self, rttm_path: str) -> Dict[str, Any]:
        """
        Read and parse an RTTM file.
        
        Args:
            rttm_path (str): Path to the RTTM file
            
        Returns:
            Dict[str, Any]: Parsed RTTM data
        """
        try:
            rttm_path = Path(rttm_path)
            
            if not rttm_path.exists():
                raise FileNotFoundError(f"RTTM file not found: {rttm_path}")
            
            segments = []
            speakers = set()
            
            with open(rttm_path, 'r') as f:
                for line_num, line in enumerate(f, 1):
                    line = line.strip()
                    
                    # Skip empty lines and comments
                    if not line or line.startswith(';'):
                        continue
                    
                    # Parse RTTM line
                    try:
                        parts = line.split()
                        
                        if len(parts) < 9 or parts[0] != 'SPEAKER':
                            logger.warning(f"Invalid RTTM line {line_num}: {line}")
                            continue
                        
                        file_id = parts[1]
                        channel = int(parts[2])
                        start_time = float(parts[3])
                        duration = float(parts[4])
                        speaker_id = parts[7]
                        
                        # Try to parse confidence
                        confidence = None
                        if parts[8] != '<NA>':
                            try:
                                confidence = float(parts[8])
                            except ValueError:
                                pass
                        
                        segment = {
                            'start': start_time,
                            'end': start_time + duration,
                            'duration': duration,
                            'speaker': speaker_id,
                            'channel': channel,
                            'confidence': confidence
                        }
                        
                        segments.append(segment)
                        speakers.add(speaker_id)
                        
                    except (ValueError, IndexError) as e:
                        logger.error(f"Error parsing RTTM line {line_num}: {line} - {e}")
                        continue
            
            # Sort segments by start time
            segments.sort(key=lambda x: x['start'])
            
            # Calculate statistics
            total_speech_time = sum(segment['duration'] for segment in segments)
            
            result = {
                'file_path': str(rttm_path),
                'segments': segments,
                'num_speakers': len(speakers),
                'speakers': sorted(list(speakers)),
                'total_segments': len(segments),
                'total_speech_time': total_speech_time,
                'avg_segment_duration': total_speech_time / len(segments) if segments else 0.0
            }
            
            logger.info(f"RTTM file parsed successfully: {len(segments)} segments, {len(speakers)} speakers")
            return result
            
        except Exception as e:
            logger.error(f"RTTM file reading failed: {e}")
            raise RuntimeError(f"Cannot read RTTM file: {e}")
    
    def validate_rttm_file(self, rttm_path: str) -> Dict[str, Any]:
        """
        Validate an RTTM file for correctness.
        
        Args:
            rttm_path (str): Path to the RTTM file
            
        Returns:
            Dict[str, Any]: Validation results
        """
        validation = {
            'valid': True,
            'errors': [],
            'warnings': [],
            'statistics': {}
        }
        
        try:
            # Read and parse the file
            rttm_data = self.read_rttm_file(rttm_path)
            
            # Check for overlapping segments from the same speaker
            segments = rttm_data['segments']
            
            for i, segment1 in enumerate(segments):
                for j, segment2 in enumerate(segments[i+1:], i+1):
                    # Check for overlaps within the same speaker
                    if segment1['speaker'] == segment2['speaker']:
                        if (segment1['start'] < segment2['end'] and 
                            segment2['start'] < segment1['end']):
                            validation['errors'].append(
                                f"Overlapping segments for speaker {segment1['speaker']}: "
                                f"[{segment1['start']:.3f}-{segment1['end']:.3f}] and "
                                f"[{segment2['start']:.3f}-{segment2['end']:.3f}]"
                            )
            
            # Check for negative durations
            for i, segment in enumerate(segments):
                if segment['duration'] <= 0:
                    validation['errors'].append(
                        f"Segment {i+1} has non-positive duration: {segment['duration']}"
                    )
            
            # Check for very short segments (potential noise)
            short_segments = [s for s in segments if s['duration'] < 0.1]  # Less than 100ms
            if short_segments:
                validation['warnings'].append(
                    f"Found {len(short_segments)} very short segments (<100ms)"
                )
            
            # Check for very long segments (potential issues)
            long_segments = [s for s in segments if s['duration'] > 60.0]  # More than 1 minute
            if long_segments:
                validation['warnings'].append(
                    f"Found {len(long_segments)} very long segments (>60s)"
                )
            
            # Calculate statistics
            validation['statistics'] = {
                'total_segments': len(segments),
                'num_speakers': rttm_data['num_speakers'],
                'total_speech_time': rttm_data['total_speech_time'],
                'avg_segment_duration': rttm_data['avg_segment_duration'],
                'min_segment_duration': min(s['duration'] for s in segments) if segments else 0,
                'max_segment_duration': max(s['duration'] for s in segments) if segments else 0,
                'speaker_distribution': {
                    speaker: len([s for s in segments if s['speaker'] == speaker])
                    for speaker in rttm_data['speakers']
                }
            }
            
            # Overall validity
            validation['valid'] = len(validation['errors']) == 0
            
        except Exception as e:
            validation['valid'] = False
            validation['errors'].append(f"Validation failed: {e}")
        
        return validation
    
    def convert_to_label_studio_format(self, rttm_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Convert RTTM data to Label Studio annotation format.
        
        Args:
            rttm_data (Dict[str, Any]): Parsed RTTM data
            
        Returns:
            Dict[str, Any]: Label Studio format annotation
        """
        try:
            # Create Label Studio regions for each segment
            regions = []
            
            for i, segment in enumerate(rttm_data['segments']):
                region = {
                    'id': f"region_{i}",
                    'from_name': "timeline",
                    'to_name': "audio",
                    'type': "timeserieslabels",
                    'value': {
                        'start': segment['start'],
                        'end': segment['end'],
                        'timeserieslabels': [segment['speaker']]
                    }
                }
                
                regions.append(region)
            
            # Create complete annotation
            annotation = {
                'result': regions,
                'created_at': datetime.now().isoformat(),
                'updated_at': datetime.now().isoformat(),
                'task': {
                    'data': {
                        'audio': '/audio/placeholder.wav'  # This would be the actual audio URL
                    }
                },
                'completed_by': 'diarization-system',
                'was_cancelled': False,
                'ground_truth': False,
                'prediction': {
                    'model_version': rttm_data.get('pipeline_version', 'unknown'),
                    'score': 1.0
                }
            }
            
            return annotation
            
        except Exception as e:
            logger.error(f"Label Studio format conversion failed: {e}")
            raise RuntimeError(f"Cannot convert to Label Studio format: {e}")
    
    def merge_rttm_files(self, rttm_files: List[str], output_path: str) -> str:
        """
        Merge multiple RTTM files into a single file.
        
        Args:
            rttm_files (List[str]): List of RTTM file paths
            output_path (str): Output path for merged file
            
        Returns:
            str: Path to the merged RTTM file
        """
        try:
            merged_segments = []
            
            for rttm_file in rttm_files:
                rttm_data = self.read_rttm_file(rttm_file)
                
                # Add file prefix to speaker IDs to avoid conflicts
                file_stem = Path(rttm_file).stem
                
                for segment in rttm_data['segments']:
                    segment_copy = segment.copy()
                    segment_copy['speaker'] = f"{file_stem}_{segment['speaker']}"
                    segment_copy['source_file'] = rttm_file
                    merged_segments.append(segment_copy)
            
            # Sort by start time
            merged_segments.sort(key=lambda x: x['start'])
            
            # Create merged result
            merged_result = {
                'segments': merged_segments,
                'num_speakers': len(set(s['speaker'] for s in merged_segments)),
                'speakers': sorted(list(set(s['speaker'] for s in merged_segments))),
                'total_segments': len(merged_segments),
                'total_speech_time': sum(s['duration'] for s in merged_segments),
                'avg_segment_duration': sum(s['duration'] for s in merged_segments) / len(merged_segments) if merged_segments else 0.0,
                'source_files': rttm_files
            }
            
            # Write merged file
            output_path = Path(output_path)
            rttm_content = self._generate_rttm_content(merged_result, output_path.stem)
            
            with open(output_path, 'w') as f:
                f.write(rttm_content)
            
            logger.info(f"RTTM files merged successfully: {output_path}")
            return str(output_path)
            
        except Exception as e:
            logger.error(f"RTTM file merging failed: {e}")
            raise RuntimeError(f"Cannot merge RTTM files: {e}")
    
    def cleanup_output_directory(self, max_age_days: int = 7):
        """
        Clean up old RTTM files from the output directory.
        
        Args:
            max_age_days (int): Maximum age in days for keeping files
        """
        try:
            import time
            
            current_time = time.time()
            max_age_seconds = max_age_days * 24 * 3600
            
            files_removed = 0
            
            for file_path in self.output_directory.glob("*.rttm"):
                file_age = current_time - file_path.stat().st_mtime
                
                if file_age > max_age_seconds:
                    file_path.unlink()
                    files_removed += 1
                    
                    # Also remove associated metadata file
                    metadata_file = file_path.with_suffix('.json')
                    if metadata_file.exists():
                        metadata_file.unlink()
            
            logger.info(f"Cleaned up {files_removed} old RTTM files")
            
        except Exception as e:
            logger.error(f"Cleanup failed: {e}")